version: '3.9'

services:
  api:
    image: ${REGISTRY_HOST}/${REGISTRY_PUBLISHER}/${PROJECT_NAME}-api:latest
    build:
      context: ../
      dockerfile: ./API_JeeWork2021/Dockerfile

  backend:
    image: ${REGISTRY_HOST}/${REGISTRY_PUBLISHER}/${PROJECT_NAME}-backend:latest
    build:
      context: ../
      dockerfile: ./BackEnd/BE_jeework/Dockerfile
