version: '3.9'

services:
  api:
    image: ${REGISTRY_HOST}/${REGISTRY_PUBLISHER}/${PROJECT_NAME}-api:latest
    build:
      context: ../
      dockerfile: ./NC_JeeSocial/NC_JeeSocial/Dockerfile

  backend:
    image: ${REGISTRY_HOST}/${REGISTRY_PUBLISHER}/${PROJECT_NAME}-backend:latest
    build:
      context: ../
      dockerfile: ./Soucre_JeeSocial/Dockerfile
