//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_JeeWork2021.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Backend {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Backend() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API_JeeWork2021.Resources.Backend", typeof(Backend).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string BACKEND_00 {
            get {
                return ResourceManager.GetString("BACKEND_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error..
        /// </summary>
        internal static string BACKEND_01 {
            get {
                return ResourceManager.GetString("BACKEND_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data..
        /// </summary>
        internal static string BACKEND_02 {
            get {
                return ResourceManager.GetString("BACKEND_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail..
        /// </summary>
        internal static string BACKEND_03 {
            get {
                return ResourceManager.GetString("BACKEND_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input wrong..
        /// </summary>
        internal static string BACKEND_04 {
            get {
                return ResourceManager.GetString("BACKEND_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more dates are not in a correct format..
        /// </summary>
        internal static string BACKEND_05 {
            get {
                return ResourceManager.GetString("BACKEND_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No language was found..
        /// </summary>
        internal static string BACKEND_06 {
            get {
                return ResourceManager.GetString("BACKEND_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists..
        /// </summary>
        internal static string BACKEND_07 {
            get {
                return ResourceManager.GetString("BACKEND_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number already exists..
        /// </summary>
        internal static string BACKEND_08 {
            get {
                return ResourceManager.GetString("BACKEND_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custommer information already save. Traveling Preference information fail..
        /// </summary>
        internal static string BACKEND_09 {
            get {
                return ResourceManager.GetString("BACKEND_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No template..
        /// </summary>
        internal static string BACKEND_10 {
            get {
                return ResourceManager.GetString("BACKEND_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset email has been sent..
        /// </summary>
        internal static string BACKEND_11 {
            get {
                return ResourceManager.GetString("BACKEND_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mail failed..
        /// </summary>
        internal static string BACKEND_12 {
            get {
                return ResourceManager.GetString("BACKEND_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exist.
        /// </summary>
        internal static string BACKEND_13 {
            get {
                return ResourceManager.GetString("BACKEND_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not confirmed..
        /// </summary>
        internal static string BACKEND_14 {
            get {
                return ResourceManager.GetString("BACKEND_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token was wrong..
        /// </summary>
        internal static string BACKEND_15 {
            get {
                return ResourceManager.GetString("BACKEND_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Phone number already exists..
        /// </summary>
        internal static string BACKEND_16 {
            get {
                return ResourceManager.GetString("BACKEND_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number or password were wrong..
        /// </summary>
        internal static string BACKEND_17 {
            get {
                return ResourceManager.GetString("BACKEND_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No currency was found..
        /// </summary>
        internal static string BACKEND_18 {
            get {
                return ResourceManager.GetString("BACKEND_18", resourceCulture);
            }
        }
    }
}
